chore: add useAppQuery hook in ProductsCard
Shopify/shopify-frontend-template-react pull request #77
Opened 2022-06-09 18:43 UTC by hheyhhay

chore: add useAppQuery hook to ProductsCard

### WHY are these changes introduced?

Fixes [#323](https://github.com/Shopify/first-party-library-planning/issues/323)
Fixes [#322](https://github.com/Shopify/first-party-library-planning/issues/322)

Implements the useAppQuery hook created in the QR Example App into the template 

### WHAT is this pull request doing?

- Removes the useAuthentification hook from the ProductsCard component and uses useAppQuery to fetch and refetch product count. 
- Removes unnecessary imports, like `button`, `useAuthentification`, `useRef`
- Imports `useAppQuery` to index and component

To TopHat : 
- `dev clone shopify-frontend-template-react`
- `git checkout <chore/add-useAppQuery>`
- In some test folder elsewhere, scaffold an app - `yarn create @shopify/app`
- `cd my-app-folder`
- `mv web/frontend web/frontend_ignore`
- `ln -s $HOME/src/github.com/Shopify/shopify-frontend-template-react web/frontend`
- `yarn dev`

2022-06-09 19:30 UTC, elanalynn approved these changes
Looks great!

2022-06-09 19:30 UTC, elanalynn commented on components/ProductsCard.jsx
> +]
nit: Can you add a blank line here?

2022-06-13 14:47 UTC, byrichardpowell requested changes
Nice! Love how this has simplified the component.  If we can simplify this further we should, see my comment.

2022-06-13 14:47 UTC, byrichardpowell commented on components/ProductsCard.jsx
>  export function ProductsCard() {
I wonder if we can simplify this component even further by removing a bunch of `useState` and `useEffect`.  E.g:

```
export function ProductsCard() {
  const [populateProduct, { isLoading: isAddingProducts }] = useShopifyMutation({
    query: PRODUCTS_QUERY,
  })

  const {
    data,
    refetch: refetchProductCount,
    isLoading: isLoadingCount,
  } = useAppQuery({
    url: '/api/products-count',
  })

  const toastMarkup = data?.count && (
    <Toast
      content="5 products created!"
    />
  )

  const handlePopulate = () => {
    Promise.all(
      Array.from({ length: 5 }).map(() =>
        populateProduct({
          input: {
            title: randomTitle(),
            variants: [{ price: randomPrice() }],
          },
        })
      )
    ).then(() => {
      refetchProductCount()
    })
  }

  return (
    <>
      {toastMarkup}
      <Card
        title="Product Counter"
        sectioned
        primaryFooterAction={{
          content: 'Populate 5 products',
          onAction: handlePopulate,
          loading: isAddingProducts,
        }}
      >
        <TextContainer spacing="loose">
          <p>
            Sample products are created with a default title and price. You can
            remove them at any time.
          </p>
          <Heading element="h4">
            TOTAL PRODUCTS
            <DisplayText size="medium">
              <TextStyle variation="strong">{isLoadingCount ? '-' : data.count }</TextStyle>
            </DisplayText>
          </Heading>
        </TextContainer>
      </Card>
    </>
  )
}
```

2022-06-13 20:27 UTC, byrichardpowell approved these changes
🔥  Just one small suggestion.  Let's get it merged as soon as the redundancy dependency is removed.

2022-06-13 20:27 UTC, byrichardpowell commented on components/ProductsCard.jsx
> +import { useEffect, useState } from 'react'
Can the useEffect dependency be removed?

2022-06-13 20:55 UTC, merged